spring:
  application:
    name: media-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      retry:
        max-attempts: 5